NavagisInternalToolSolution/registerproject-spice/Models/Client.cs
using System.ComponentModel.DataAnnotations;
namespace RegisterProject_Spice.Pages.Models
{
    public class Client
    {
        public int Id { get; set; }

        [Required]
        [StringLength(255)]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [StringLength(255)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [StringLength(255)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        public BillingAccount BillingAccount { get; set; }

        [Required]
        public int BillingAccountId { get; set; }
    }
}

NavagisInternalToolSolution/registerproject-spice/Controllers/BillingAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using RegisterProject_Spice.Pages.Models;
using RegisterProject_Spice.Utilities;

namespace RegisterProject_Spice.Controllers
{
    [AdminRequiresAuthentication]
    public class BillingAccountsController : Controller
    {
        private ApplicationDbContext db;

        public BillingAccountsController(ApplicationDbContext context)
        {
            db = context;
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }

        public IActionResult Index()
        {
            return View(db.BillingAccounts.ToList());
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: BillingAccounts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[IgnoreAntiforgeryToken]
        public ActionResult Create(BillingAccount billingAccount)
        {
            if (ModelState.IsValid)
            {
                db.BillingAccounts.Add(billingAccount);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(billingAccount);
        }

        // GET: BillingAccounts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            BillingAccount billingAccount = db.BillingAccounts.Find(id);
            if (billingAccount == null)
            {
                return new StatusCodeResult(400);
            }
            return View(billingAccount);
        }

        // POST: BillingAccounts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[IgnoreAntiforgeryToken]
        public ActionResult Edit(BillingAccount billingAccount)
        {
            if (ModelState.IsValid)
            {
                var billingAccountDb = db.BillingAccounts.SingleOrDefault(s => s.Id == billingAccount.Id);
                billingAccountDb.BillingAccountName = billingAccount.BillingAccountName;
                billingAccountDb.Description = billingAccount.Description;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(billingAccount);
        }

        // GET: BillingAccounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            BillingAccount billingAccount = db.BillingAccounts.Find(id);
            if (billingAccount == null)
            {
                return new StatusCodeResult(400);
            }
            return View(billingAccount);
        }

        // GET: BillingAccounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            BillingAccount billingAccount = db.BillingAccounts.Find(id);
            if (billingAccount == null)
            {
                return new StatusCodeResult(400);
            }
            return View(billingAccount);
        }

        // POST: BillingAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //[IgnoreAntiforgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BillingAccount billingAccount = db.BillingAccounts.Find(id);
            db.BillingAccounts.Remove(billingAccount);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

NavagisInternalToolSolution/registerproject-spice/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RegisterProject_Spice.Pages.Models;
using RegisterProject_Spice.Utilities;


namespace RegisterProject_Spice.Controllers
{
    [AdminRequiresAuthentication]
    public class ClientsController : Controller
    {
        private ApplicationDbContext db;

        public ClientsController(ApplicationDbContext context)
        {
            db = context;
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
        }

        public IActionResult Index()
        {
            var clients = db.Clients.Include(c => c.BillingAccount);
            return View(clients.ToList());
        }
        // GET: Clients/Create
        public ActionResult Create()
        {
            ViewBag.BillingAccountId = new SelectList(db.BillingAccounts, "Id", "BillingAccountName");
            return View();
        }

        // POST: Clients/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[IgnoreAntiforgeryToken]
        public ActionResult Create(Client client)
        {
            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BillingAccountId = new SelectList(db.BillingAccounts, "Id", "BillingAccountName", client.BillingAccountId);
            return View(client);
        }

        // GET: Clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return new StatusCodeResult(400);
            }
            var billingAccountDb = db.BillingAccounts.SingleOrDefault(s => s.Id == client.BillingAccountId);
            ViewBag.BillingAccountId = billingAccountDb.BillingAccountName;
            return View(client);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return new StatusCodeResult(400);
            }
            ViewBag.BillingAccountId = new SelectList(db.BillingAccounts, "Id", "BillingAccountName", client.BillingAccountId);
            return View(client);
        }

        // POST: Clients/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[IgnoreAntiforgeryToken]
        public ActionResult Edit(Client client)
        {
            if (ModelState.IsValid)
            {
                var clientDb = db.Clients.SingleOrDefault(s => s.Id == client.Id);
                clientDb.Email = client.Email;
                clientDb.FirstName = client.FirstName;
                clientDb.LastName = client.LastName;
                clientDb.BillingAccountId = client.BillingAccountId;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BillingAccountId = new SelectList(db.BillingAccounts, "Id", "BillingAccountName", client.BillingAccountId);
            return View(client);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult(400);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return new StatusCodeResult(400);
            }
            var billingAccountDb = db.BillingAccounts.SingleOrDefault(s => s.Id == client.BillingAccountId);
            ViewBag.BillingAccountId = billingAccountDb.BillingAccountName;
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        //[IgnoreAntiforgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

NavagisInternalToolSolution/registerproject-spice/Views/Clients/Create.cshtml
@model RegisterProject_Spice.Pages.Models.Client

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>Client Emails</h2>
<div class="table-border-with-shadow">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Create</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BillingAccountId, "BillingAccountId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BillingAccountId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BillingAccountId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

NavagisInternalToolSolution/registerproject-spice/Views/Clients/Delete.cshtml
@model RegisterProject_Spice.Pages.Models.Client

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
@{
    var BillingAccountId = ViewBag.BillingAccountId;
}

<h2>Client Emails</h2>
<div class="table-border-with-shadow">
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Delete</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.BillingAccount.BillingAccountName)
            </dt>

            <dd>
                @BillingAccountId
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

NavagisInternalToolSolution/registerproject-spice/Views/Clients/Details.cshtml
@model RegisterProject_Spice.Pages.Models.Client

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
@{
    var BillingAccountId = ViewBag.BillingAccountId;
}
<h2>Client Emails</h2>
<div class="table-border-with-shadow">
    <div>
        <h4>Details</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.BillingAccount.BillingAccountName)
            </dt>

            <dd>
                @BillingAccountId
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

NavagisInternalToolSolution/registerproject-spice/Views/Clients/Edit.cshtml
@model RegisterProject_Spice.Pages.Models.Client

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>Client Emails</h2>
<div class="table-border-with-shadow">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Edit</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BillingAccountId, "BillingAccountId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("BillingAccountId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BillingAccountId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

NavagisInternalToolSolution/registerproject-spice/Views/Clients/Index.cshtml
@model IEnumerable<RegisterProject_Spice.Pages.Models.Client>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<h2>Client Emails</h2>
<div class="table-border-with-shadow">

    <div class="row">
        <div class="col-lg-6">
            <p>
                @Html.ActionLink("Create New", "Create")
                <!--
                @Html.ActionLink("Add Client Email", "Create", "Clients", null, new { @class = "btn btn-info" })
                @Html.ActionLink("Go to Billing Account List", "Index", "BillingAccounts", null, new { @class = "btn btn-info" })
                -->
            </p>
        </div><!-- /.col-lg-6 -->
        <div class="col-lg-6">
            &nbsp;
            <!--
            <div class="input-group">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">Go!</button>
                </span>
                <input type="text" class="form-control" placeholder="Search for...">

                </div>
                          -->
        </div><!-- /.col-lg-6 -->
    </div><!-- /.row -->
    <table class="table" id="customTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BillingAccount.BillingAccountName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BillingAccount.BillingAccountName)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
@section scripts
{
    <script>
        $(document).ready(function () {
            $("#customTable").DataTable();
        });
    </script>
}